language: node_js
node_js:
  - 0.10
before_script:
  - npm i -g gulp jspm codeclimate-test-reporter 
  - npm i
  - jspm i
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - jspm dl-loader --Babel
  - gulp test:unit
  - gulp test:e2e

